// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: CONTROLBOX

#ifndef UI_SCREENINTERFACE_H
#define UI_SCREENINTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenInterface
extern void ui_ScreenInterface_screen_init(void);
extern void ui_ScreenInterface_screen_destroy(void);
extern void ui_event_ScreenInterface(lv_event_t * e);
extern lv_obj_t * ui_ScreenInterface;
extern void ui_event_ArcIndicator(lv_event_t * e);
extern lv_obj_t * ui_ArcIndicator;
extern lv_obj_t * ui_LogoQuasizero;
extern lv_obj_t * ui_NumberSpeed;
extern lv_obj_t * ui_LabelSpeed;
extern lv_obj_t * ui_DimensionUnit;
extern void ui_event_ButtonDirection(lv_event_t * e);
extern lv_obj_t * ui_ButtonDirection;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

