// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: CONTROLBOX

#include "../ui.h"

lv_obj_t * ui_ScreenInterface;
lv_obj_t * ui_ArcIndicator;
lv_obj_t * ui_LogoQuasizero;
lv_obj_t * ui_NumberSpeed;
lv_obj_t * ui_LabelSpeed;
lv_obj_t * ui_DimensionUnit;
lv_obj_t * ui_ButtonDirection;

// event funtions
void ui_event_ScreenInterface(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        onScreenLoaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        onScreenUnloaded(e);
    }
}

void ui_event_ArcIndicator(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onArcValueChanged(e);
    }
}

void ui_event_ButtonDirection(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        onDirectionChecked(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        onDirectionUnchecked(e);
    }
}

// build funtions

void ui_ScreenInterface_screen_init(void)
{
    ui_ScreenInterface = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenInterface, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenInterface, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenInterface, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcIndicator = lv_arc_create(ui_ScreenInterface);
    lv_obj_set_width(ui_ArcIndicator, 215);
    lv_obj_set_height(ui_ArcIndicator, 215);
    lv_obj_set_align(ui_ArcIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcIndicator, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ArcIndicator, LV_SCROLLBAR_MODE_OFF);
    lv_arc_set_range(ui_ArcIndicator, 0, 500);
    lv_arc_set_value(ui_ArcIndicator, 100);
    lv_arc_set_bg_angles(ui_ArcIndicator, 115, 65);
    lv_obj_set_style_arc_color(ui_ArcIndicator, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcIndicator, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcIndicator, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcIndicator, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcIndicator, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcIndicator, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcIndicator, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LogoQuasizero = lv_img_create(ui_ScreenInterface);
    lv_img_set_src(ui_LogoQuasizero, &ui_img_quasizero_png);
    lv_obj_set_width(ui_LogoQuasizero, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoQuasizero, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LogoQuasizero, 21);
    lv_obj_set_y(ui_LogoQuasizero, -70);
    lv_obj_set_align(ui_LogoQuasizero, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LogoQuasizero, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_LogoQuasizero, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_transform_zoom(ui_LogoQuasizero, 175, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumberSpeed = lv_label_create(ui_ScreenInterface);
    lv_obj_set_width(ui_NumberSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumberSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumberSpeed, 0);
    lv_obj_set_y(ui_NumberSpeed, 25);
    lv_obj_set_align(ui_NumberSpeed, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_NumberSpeed, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_NumberSpeed, "05.0");
    lv_obj_clear_flag(ui_NumberSpeed, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_NumberSpeed, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_NumberSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumberSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumberSpeed, &ui_font_QZdata100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_NumberSpeed, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeed = lv_label_create(ui_ScreenInterface);
    lv_obj_set_width(ui_LabelSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed, 60);
    lv_obj_set_y(ui_LabelSpeed, -6);
    lv_obj_set_align(ui_LabelSpeed, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelSpeed, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_LabelSpeed, "extrusion\nspeed");
    lv_obj_clear_flag(ui_LabelSpeed, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_LabelSpeed, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_LabelSpeed, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeed, &ui_font_QZdata15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DimensionUnit = lv_label_create(ui_ScreenInterface);
    lv_obj_set_width(ui_DimensionUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DimensionUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DimensionUnit, 50);
    lv_obj_set_y(ui_DimensionUnit, 21);
    lv_obj_set_align(ui_DimensionUnit, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_DimensionUnit, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_DimensionUnit, "mm/s");
    lv_obj_clear_flag(ui_DimensionUnit, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_DimensionUnit, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_DimensionUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DimensionUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DimensionUnit, &ui_font_QZdata15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonDirection = lv_btn_create(ui_ScreenInterface);
    lv_obj_set_width(ui_ButtonDirection, 30);
    lv_obj_set_height(ui_ButtonDirection, 30);
    lv_obj_set_x(ui_ButtonDirection, 0);
    lv_obj_set_y(ui_ButtonDirection, 92);
    lv_obj_set_align(ui_ButtonDirection, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonDirection, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_ButtonDirection,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ButtonDirection, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_ButtonDirection, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonDirection, lv_color_hex(0x1CD957), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDirection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonDirection, &ui_img_clock_white20x20_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonDirection, &ui_img_anticlockwise_white20x20_png, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_ArcIndicator, ui_event_ArcIndicator, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonDirection, ui_event_ButtonDirection, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenInterface, ui_event_ScreenInterface, LV_EVENT_ALL, NULL);

}

void ui_ScreenInterface_screen_destroy(void)
{
    if(ui_ScreenInterface) lv_obj_del(ui_ScreenInterface);

    // NULL screen variables
    ui_ScreenInterface = NULL;
    ui_ArcIndicator = NULL;
    ui_LogoQuasizero = NULL;
    ui_NumberSpeed = NULL;
    ui_LabelSpeed = NULL;
    ui_DimensionUnit = NULL;
    ui_ButtonDirection = NULL;

}
