// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: CONTROLBOX

#ifndef _CONTROLBOX_UI_H
#define _CONTROLBOX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_ScreenInterface.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_quasizero_name_png);    // assets/QUASIZERO_name.png
LV_IMG_DECLARE(ui_img_clock_white20x20_png);    // assets/clock_white20x20.png
LV_IMG_DECLARE(ui_img_anticlockwise_white20x20_png);    // assets/anticlockwise_white20x20.png

// FONTS
LV_FONT_DECLARE(ui_font_QZdata15);
LV_FONT_DECLARE(ui_font_QZdata65);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
