// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: CONTROLBOX

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onScreenLoaded(lv_event_t * e);
void onScreenUnloaded(lv_event_t * e);
void onArcValueChanged(lv_event_t * e);
void onDirectionChecked(lv_event_t * e);
void onDirectionUnchecked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
