// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: CONTROLBOX

#include "ui.h"

void onScreenLoaded(lv_event_t * e)
{
	// Your code here
}

void onScreenUnloaded(lv_event_t * e)
{
	// Your code here
}

void onArcValueChanged(lv_event_t * e)
{
	// Your code here
}

void onDirectionChecked(lv_event_t * e)
{
	// Your code here
}

void onDirectionUnchecked(lv_event_t * e)
{
	// Your code here
}
